Update number-utils.ts
Fix: src/utils/number-utils.ts(28,33): error TS2550: Property 'replaceAll' does not exist on type 'string'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2021' or later.